version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - web

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - api/.env
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
